config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # 수정
  root 'posts#index'

  get 'posts/new' => 'posts#new'

  post 'posts/create' => 'posts#create'

  get 'posts/show/:id' => 'posts#show', as: 'post' # as 추가

  get 'posts/edit/:id' => 'posts#edit'

  post 'posts/update/:id' => 'posts#update'

  delete 'posts/destroy/:id' => 'posts#destroy'

  post 'posts/like/:id' => 'posts#like', as: 'post_like' # 좋아요
  post 'posts/dislike/:id' => 'posts#dislike', as: 'post_dislike' # 싫어요


  post 'comments/create' => 'comments#create'

  post 'comments/destroy/:id' => 'comments#destroy'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user # 변경
	belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comment
	has_many :like
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :post
  has_many :comment # 변경
  has_many :like # 추가
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    # check 메소드의 정의
    def check_authorization!
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_authorization!

  def create
    @comment = Comment.new
    # params :comment_ xxx 로 변경
    @comment.user_id = params[:comment_user_id]
    @comment.post_id = params[:comment_post_id]
    @comment.content = params[:comment_content]
    @comment.save
    redirect_to post_path(@comment.post_id) # 생성 후 해당 post로 리다이렉션
  end

  def destroy
    # where절을 find로 변경
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(params[:post_id]) # 삭제 후 해당 post로 리다이렉션
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_authorization!

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new
    @post.user_id = params[:input_user]
    @post.title = params[:input_title]
    @post.email = current_user.email
    @post.content = params[:input_content]
    @post.like_count = 0
    @post.save
    redirect_to post_path(@post.id)
  end

  def show
    @post = Post.find params[:id]
    @comments = Comment.where(post_id: @post.id)
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)

  end

  def update
    @post = Post.find params[:id]
    @post.user_id = params[:input_user]
    @post.title = params[:input_title]
    @post.content = params[:input_content]
    @post.save
    redirect_to post_path(@post)
  end

  # edit 아래부분 update로 이동
  def edit
    @post = Post.find params[:id]
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to '/'
  end

  # 좋아요
  def like

    # 좋아요를 누를 post 찾기
    @post = Post.find params[:id]
    @post.like_count += 1
    @post.save 

    # like 생성
    @like = Like.new
    @like.post_id = @post.id
    @like.user_id = current_user.id
    @like.save

    redirect_to post_path(@post)
  end

  # 싫어요 
  def dislike 
    
    @post = Post.find params[:id]
    @like = Like.find_by(post_id: @post.id)
    
    if @post.like_count - 1 >= 0
      @post.like_count -= 1 
      @like.destroy
    else
      @post.like_count = 0
    end

    @post.save

    redirect_to post_path(@post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>

  <body>
    
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/posts/new">New! <span class="sr-only">(current)</span></a>
            </li>
            
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            
            <button class="btn btn-outline-success my-2 my-sm-0">
              <% if user_signed_in? %>
                <a href="/users/sign_out" data-method="delete"><h4>Sign out</h4></a>
              <% else %>
                <a href="/users/sign_in"><h4>Sign in</h4></a>
              <% end  %>
            </button>
          </form>
        </div>
        </div>
      </nav>
    <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Post edit</h1>
<!-- method put에서 post로 변경 -->
<form action="/posts/update/<%= @post.id %>" method="post">
  <!-- csrf token 추가 -->
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="input_user" value="<%= current_user.id %>">
  <p>title : <input type="text" name="input_title" value="<%= @post.title %>"></p>
  <div>content : <textarea name="input_content" cols="30" rows="10"><%= @post.content %></textarea></div>
  <input type="submit" value="edit">
</form>

app/views/posts/index.html.erb
<h1>All Post</h1>
<% @posts.each do |post| %>
	<table class="table">
		<thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">title</th>
		      <th scope="col">user</th>
		    </tr>
		 </thead>
		 <tbody>
		    <tr>
		      <th scope="row"><%= post.id %></th>
		      <td><a href="/posts/show/<%= post.id %>"><%= post.title %></td>
		      <td><%= post.email %></td>
		    </tr>
		</tbody>
	</table>
<% end %>	

app/views/posts/new.html.erb
<h1>new Post</h1>
<form action="/posts/create" method="post" enctype="multipart/form-data">
  <!-- csrf token 추가 -->
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
  <input type="hidden" name="input_user" value="<%= current_user.id %>">
  <p>title : <input type="text" name="input_title"></p>
  <div>content : <textarea name="input_content" cols="30" rows="10"></textarea></div>
  <input type="submit" value="save">
</form>

app/views/posts/show.html.erb
<p>user : <%= @post.user.email %></p>
<p>title : <%= @post.title %></p>
<p>content : <%= @post.content%></p>

    <% if @like %>
      <%= button_to "좋아요 취소", post_dislike_path(@post) %> 
    <% else %>
      <span>
        <%= button_to "좋아요", post_like_path(@post) %>
    <% end %>
     <p class="like_count"> <%= @post.like_count %> </p>

<%# current_user -> current_user.id %>
<% if @post.user_id == current_user.id %>
  <div>
    <a href="/posts/edit/<%= @post.id %>">[edit]</a>
    <a href="/posts/destroy/<%= @post.id %>" data-method="delete" data-confirm="delete?">[delete]</a>
  </div>
<% end %>
<hr>
<div>
  <h2>comment</h2>
  <!-- method get에서 post로 변경 -->
  <form action="/comments/create" method="post">
    <!-- csrf token 추가 -->
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
    <input type="hidden" name="comment_user_id" value="<%= current_user.id %>">
    <input type="hidden" name="comment_post_id" value="<%= @post.id %>">
    <input type="text" name="comment_content">
    <input type="submit" value="comment">
    
  </form>
  <% @comments.each do |c| %>
    <p>
      <%= c.user.email %> : <%= c.content %>
    </p>
    <%# c.user -> c.user_id로 변경%>
    <% if current_user.id == c.user_id %>
        <form action="/comments/destroy/<%= c.id %>" method="post">
          <!-- csrf token 추가 -->
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
          <input type="hidden" name="post_id" value="<%= @post.id %>">
          <input type="submit" value="delete" >
        </form>
    <% end %>


  <% end %>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>